import time

def _invoke_with_retry(chain, inputs: dict, max_retries: int = 3) -> str:
    """Retries LLM calls on rate limit errors with exponential backoff."""
    for attempt in range(max_retries):
        try:
            return chain.invoke(inputs)
        except Exception as e:
            if "429" in str(e) and attempt < max_retries - 1:
                wait = 30 * (attempt + 1)
                logger.warning(f"Rate limited — waiting {wait}s (attempt {attempt + 1}/{max_retries})")
                time.sleep(wait)
            else:
                raise

import logging
from datetime import datetime
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from financial_analyst.state import AnalystState
from financial_analyst.config import settings

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Prompt
# ---------------------------------------------------------------------------

REPORTER_PROMPT = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a financial report formatter at a top investment bank.
Your job is to take a raw analysis and format it into a polished,
publication-ready investment research report.

The report must follow this exact structure:

# [COMPANY NAME] ([TICKER]) — Investment Research Report
**Period:** [period] | **Date:** [date] | **Sentiment:** [BULLISH/NEUTRAL/BEARISH]

---

## Executive Summary
(3-4 sentence overview — most important finding first)

---

## Key Metrics Snapshot
(Formatted table of the most important numbers)

---

## 1. Revenue & Growth Analysis
(From the analysis — well formatted, citations included)

## 2. Profitability Analysis
(From the analysis)

## 3. Balance Sheet Health
(From the analysis)

## 4. Free Cash Flow Analysis
(From the analysis)

## 5. Forward Guidance & Outlook
(From the analysis)

## 6. Key Risks
(Formatted as a risk table with severity ratings)

## 7. Investment Thesis
(Bull case, bear case, overall verdict)

---

## Data Sources
(List all sources used)

---

*This report was generated by an AI financial analysis system.
It is for informational purposes only and does not constitute
investment advice.*

Formatting rules:
- Use markdown tables for numerical data
- Bold all key numbers inline (e.g. **$94.3B revenue**)
- Use > blockquotes for direct management quotes
- Every section must have at least 2 substantive paragraphs
- Severity ratings for risks: 🔴 High / 🟡 Medium / 🟢 Low"""
    ),
    (
        "human",
        """Format the following analysis into a polished research report.

COMPANY: {company_name} ({ticker})
PERIOD: {period}
DATE: {date}

STRUCTURED DATA:
{structured_data}

RAW ANALYSIS:
{analysis}

CRITIQUE FEEDBACK (for quality context):
{critique}

Produce the complete formatted investment research report."""
    )
])


# ---------------------------------------------------------------------------
# LLM setup
# ---------------------------------------------------------------------------

def _get_llm():
    return ChatOpenAI(
        model=settings.model_name,
        openai_api_key=settings.openrouter_api_key,
        openai_api_base=settings.openrouter_base_url,
        temperature=0.2,  # slight creativity for readable prose
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _build_metrics_context(data: dict) -> str:
    """Formats structured data into a clean context block for the reporter."""
    if not data:
        return "No structured data available."

    lines = []
    inc = data.get("income_statement", {})
    bal = data.get("balance_sheet", {})
    met = data.get("key_metrics", {})

    metric_map = {
        "Revenue": (inc.get("revenue"), "${:,.1f}M"),
        "Revenue Growth YoY": (inc.get("revenue_growth_yoy"), "{:.1f}%"),
        "Gross Margin": (inc.get("gross_margin"), "{:.1f}%"),
        "Operating Income": (inc.get("operating_income"), "${:,.1f}M"),
        "Net Income": (inc.get("net_income"), "${:,.1f}M"),
        "Diluted EPS": (inc.get("eps_diluted"), "${:.2f}"),
        "EBITDA": (inc.get("ebitda"), "${:,.1f}M"),
        "Cash": (bal.get("cash_and_equivalents"), "${:,.1f}M"),
        "Total Debt": (bal.get("total_debt"), "${:,.1f}M"),
        "Debt/Equity": (bal.get("debt_to_equity"), "{:.2f}x"),
        "P/E Ratio": (met.get("pe_ratio"), "{:.1f}x"),
        "ROE": (met.get("roe"), "{:.1f}%"),
        "Free Cash Flow": (met.get("free_cash_flow"), "${:,.1f}M"),
    }

    for label, (value, fmt) in metric_map.items():
        if value is not None:
            try:
                lines.append(f"{label}: {fmt.format(value)}")
            except (ValueError, TypeError):
                lines.append(f"{label}: {value}")

    return "\n".join(lines) if lines else "No metrics available."


def _build_citations(state: AnalystState) -> list[str]:
    """
    Builds a citations list from state.
    Combines any citations accumulated during ingestion
    with the input source reference.
    """
    citations = list(state.get("citations", []))
    input_type = state.get("input_type", "text")
    user_input = state.get("user_input", "")

    if input_type == "pdf":
        citations.insert(0, f"Primary source: {user_input} (PDF filing)")
    elif input_type == "ticker":
        citations.insert(0, f"Primary source: {user_input} — SEC EDGAR + Tavily search")
    elif input_type == "url":
        citations.insert(0, f"Primary source: {user_input}")
    else:
        citations.insert(0, "Primary source: User-provided text")

    # Deduplicate while preserving order
    seen = set()
    unique = []
    for c in citations:
        if c not in seen:
            seen.add(c)
            unique.append(c)

    return unique


# ---------------------------------------------------------------------------
# Node
# ---------------------------------------------------------------------------

def report_generator(state: AnalystState) -> dict:
    """
    LangGraph node — final node in the graph.
    Transforms raw analysis into a polished markdown report.

    Reads:  state["analysis"], state["structured_data"],
            state["critique"], state["citations"]
    Writes: state["final_report"], state["citations"]
    """
    analysis = state.get("analysis", "").strip()
    structured_data = state.get("structured_data", {})
    critique_text = state.get("critique", "")

    company_name = structured_data.get("company_name") or "Unknown Company"
    ticker = structured_data.get("ticker") or "N/A"
    period = structured_data.get("period") or "Unknown Period"
    date = datetime.now().strftime("%B %d, %Y")

    if not analysis:
        return {
            "final_report": "# Report Generation Failed\n\nNo analysis was produced.",
            "errors": ["report_generator: received empty analysis."],
        }

    logger.info(f"Generating final report for {company_name} ({ticker})")

    try:
        llm = _get_llm()
        chain = REPORTER_PROMPT | llm | StrOutputParser()

        final_report = _invoke_with_retry(chain,{
            "company_name": company_name,
            "ticker": ticker,
            "period": period,
            "date": date,
            "structured_data": _build_metrics_context(structured_data),
            "analysis": analysis,
            "critique": critique_text or "No critique available.",
        })

        # Build citations and append to report
        citations = _build_citations(state)
        if citations:
            citations_block = "\n\n---\n\n## Data Sources\n" + "\n".join(
                f"- {c}" for c in citations
            )
            # Only append if not already in report
            if "## Data Sources" not in final_report:
                final_report += citations_block

        logger.info(f"Report generated — {len(final_report)} chars")

        return {
            "final_report": final_report,
            "citations": citations,
            "errors": [],
        }

    except Exception as e:
        logger.error(f"report_generator failed: {e}")
        # Fallback — return raw analysis as the report
        fallback = f"# {company_name} Analysis\n\n{analysis}"
        return {
            "final_report": fallback,
            "errors": [f"report_generator formatting failed: {str(e)}"],
        }